import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({
    service: {
      name: "Snoopy",
      version: "0.2",
      description: "Website teardown product where distinct critics inspect a page, speak in first person, and produce before/after improvement work.",
      capabilities: [
        "persistent core cast, including MIKE THE CREATOR, with personality-facet coverage",
        "LLM-powered customer-owned agent generator with deterministic fallback when credentials are absent",
        "saved customer agents can join a website run from the browser session",
        "run setup shows saved customer-agent memory, critique lenses, source diet, and tastes before selection",
        "run setup shows a saved customer-agent's latest conversation-memory signal before selection when prior run history exists",
        "run setup summarizes repeated saved-agent relationship patterns when enough prior stance history exists",
        "agent profiles show inbound conversation memory for other agents that respond to a saved or core agent",
        "agent profiles include face initials, voice, backstory, tastes, memories, source diet, and day plan",
        "agents page presents the core cast as a living cast room with memory, source diet, day plan, first-person critique moments, and room to expand beyond the starting panel",
        "agents page promotes browser-saved customer agents as active cast members with latest-run memory and a run-with-this-agent path",
        "core cast profile pages expose weighted personality facets so buyers can see why agents differ",
        "agent profiles explain how an agent's personality weights differ from the rest of the core cast",
        "agent profiles can show recent generated-run reactions from browser session memory when the agent has participated in a run",
        "customer-owned profile pages can update saved agent name, role, face, voice, backstory, memories, tastes, blind spots, critique lenses, source diet, personality facets, customer relationship, exclusivity, and day plan",
        "core and browser-saved customer agents have profile routes at /agents/{agentId}",
        "custom agent creation during run setup",
        "controlled persona voice settings, including bounded mild or moderate profanity when it fits the evaluator",
        "prior-cycle memory and visible disagreement tracking",
        "report detail includes a conversation map with stance counts and visible agent-to-agent links",
        "report detail opens with a before/after workshop flow covering conversation, marked screen evidence, prior-run change, consensus health, and the first fix to ship",
        "report detail exposes Overview, Agents, Screens, Fixes, Sources, and Export board navigation so agents and humans can jump to the right workspace area",
        "report detail shows a top customer-owned agent signal with latest thought, reaction count, credited fixes, source habit, and stance mix",
        "report detail compares the core-cast read with the customer-owned agent contribution before the long recommendation list",
        "report detail surfaces customer-owned agent influence near the workshop flow with reaction counts, credited fixes, and source habits",
        "report recommendation cards and implementation-plan fixes show the agent relationship behind each fix when reaction links are available",
        "report recommendation cards keep the first evidence module rich and collapse repeated evidence receipts on later fixes",
        "report recommendation cards render linked agent relationships as compact conversation threads",
        "report recommendation cards combine affected region, agent relationship, and screen evidence into a Why this fix exists module",
        "report recommendation cards and implementation-plan fixes credit customer-owned agents when they shape a recommendation",
        "report detail can filter recommendations by the agent relationship that produced the fix",
        "report detail summarizes the visible fixes produced by a selected agent relationship filter",
        "copied fix handoffs preserve selected relationship-filter context when the user copies from a filtered fix list",
        "bulk implementation-plan copy and download apply the visible report filters and preserve selected source or relationship context",
        "filtered implementation plans preview the exact visible fixes before copy or download",
        "filtered implementation plans compare visible fix count against the full recommendation set",
        "filtered implementation plans state how many recommendation fixes are hidden by the current filters",
        "report recommendation cards preview the exact copied fix handoff before the user puts it on the clipboard",
        "report detail shows comparison URLs and market/news context as visible agent reading evidence",
        "report reaction bubbles show when an agent used a visible comparison or market source",
        "report detail can filter reactions and recommendations by the comparison or market source that shaped them",
        "recommendation cards combine the source-backed fix receipt with a visual source influence panel linking an outside read to the agent translation behind a fix",
        "copied fix handoffs preserve selected source-filter context when the user copies from a source-filtered fix list",
        "copied fix handoffs and implementation plans include source references when source-linked reactions shaped a fix",
        "recommendation cards show source-backed fix evidence before the exact task preview",
        "report detail shows before/after hypotheses with current agent read, improved state, and evidence",
        "report detail uses captured screen evidence from generated runs as the before state when available",
        "screen evidence can include captured viewport annotations for visible headings, actions, forms, images, and content regions",
        "comparison URL and market/news context ingestion",
        "mobile, tablet, laptop, and desktop device checks",
        "read-only browser navigation with destructive actions blocked",
        "journey trace, first-person reactions, findings, before/after recommendations, and critic-specific evidence",
        "exportable recommendation work items with affected regions, implementation steps, and acceptance criteria",
        "report artifact manifest with markdown implementation queue metadata",
        "report detail agent-memory cards show each persona profile beside that persona's latest preserved report reaction",
        "implementation queue markdown includes agent judgment context from preserved persona reactions",
        "implementation queue markdown includes captured screen evidence annotations when available",
        "implementation queue markdown includes operational boundaries for credentials, persistence, and destructive actions",
        "copyable recommendation fix handoff for marketer-to-agent handoff",
        "bulk implementation plan export for the full recommendation set",
        "downloadable and fetchable markdown implementation queue artifacts",
        "production persistence writes report artifact records for declared report artifacts",
        "reports preserve customer-owned agent profile fields, including memory, source diet, and day plan",
        "self-audit runs can seed browser localStorage so saved-agent states are testable with the same artifact pipeline",
        "deployment documentation lists production environment variables, validation commands, smoke checks, and credential boundaries",
      ],
    },
    plans: [
      {
        id: "pilot",
        name: "Pilot",
        price: "contact",
        currency: "USD",
        availableWithoutCredentials: false,
        includes: ["critic conversation", "before/after recommendations", "custom critics"],
      },
      {
        id: "production",
        name: "Production",
        price: "contact",
        currency: "USD",
        availableWithoutCredentials: false,
        includes: ["persisted runs", "workspace history", "report artifact records", "billing portal", "deployment support"],
      },
    ],
    api: {
      createRun: {
        method: "POST",
        path: "/api/runs",
        contentType: "application/json",
        minimumBody: {
          targetUrl: "https://example.com",
          goal: "Understand pricing and decide whether to start a trial.",
        },
      },
      listRuns: {
        method: "GET",
        path: "/api/runs",
      },
      readReport: {
        method: "GET",
        path: "/api/runs/{runId}",
      },
      readImplementationQueue: {
        method: "GET",
        path: "/api/runs/{runId}/implementation-queue",
        responseType: "text/markdown",
      },
      generateAgent: {
        method: "POST",
        path: "/api/agents/generate",
        contentType: "application/json",
        minimumBody: {
          brief: "Create a customer-owned brand guardian for homepage clarity and premium visual quality.",
          customerName: "Acme Growth",
          tone: "plainspoken",
          customerOwned: true,
        },
      },
      readAgentProfile: {
        method: "GET",
        path: "/agents/{agentId}",
        responseType: "html",
      },
    },
    examples: {
      createRun: {
        request: {
          method: "POST",
          path: "/api/runs",
          headers: { "content-type": "application/json" },
          body: {
            targetUrl: "https://example.com",
            goal: "Find why a busy buyer would bounce before understanding the offer.",
            comparisonUrls: ["https://www.hotjar.com"],
            marketContext: "Judge the page like a paid growth audit. Show what works, what is hard to read, and what should change next.",
            maxPages: 1,
          },
        },
        responseShape: {
          report: "Report payload with personas, reactions, findings, recommendations, screen evidence, before/after hypotheses, and artifacts.",
          events: "Runner trace events in chronological order.",
          persistence: "Persistence status and reopened run reference when available.",
        },
      },
      generateAgent: {
        request: {
          method: "POST",
          path: "/api/agents/generate",
          headers: { "content-type": "application/json" },
          body: {
            brief: "Create a customer-owned low-vision conversion reviewer for checkout readability.",
            customerName: "Acme Growth",
            tone: "plainspoken",
            customerOwned: true,
          },
        },
        responseShape: {
          agent: "GeneratedAgent profile that can be saved in `snoopy.savedAgents` and passed into `additionalPersonas` on /api/runs.",
          generation: "Generation status: `llm`, `fallback`, or `deterministic`, plus an optional reason.",
        },
      },
      readImplementationQueue: {
        request: {
          method: "GET",
          path: "/api/runs/{runId}/implementation-queue",
          accept: "text/markdown",
        },
        responseShape: "Markdown work packet with agent judgment context, recommendation fixes, acceptance criteria, source references, screen evidence, and operational boundaries when available.",
      },
    },
    fieldContracts: {
      createRunBody: {
        required: ["targetUrl"],
        optional: ["runId", "goal", "comparisonUrls", "marketContext", "additionalPersonas", "devices", "maxPages"],
        notes: [
          "`targetUrl` must be an absolute URL that Snoopy can read without destructive actions.",
          "`additionalPersonas` accepts PersonaProfile-compatible objects, including customer-owned agents saved from the generator.",
          "`comparisonUrls` and `marketContext` become visible reading evidence when reactions or recommendations use them.",
          "`maxPages` should stay low for smokeable runs; use 1 when testing product surfaces.",
        ],
      },
      generatedAgent: {
        required: [
          "id",
          "name",
          "role",
          "face",
          "voice",
          "goal",
          "backstory",
          "memories",
          "tastes",
          "blindSpots",
          "motivations",
          "likes",
          "deviceHabits",
          "skepticism",
          "critiqueLens",
          "voiceSettings",
          "personalityFacets",
          "dayPlan",
          "sourceDiet",
          "customerRelationship",
          "privateExclusive",
          "customerOwned",
        ],
        notes: [
          "`personalityFacets` values are weights from 0 to 1 for introversion, extraversion, sensing, intuition, thinking, feeling, judging, and perceiving.",
          "`voiceSettings.profanityLevel` is controlled and may be `none`, `mild`, or `moderate`; it is not a substitute for useful critique.",
          "`customerOwned: true` marks the profile as private workspace context, not public core-cast data.",
        ],
      },
      reaction: {
        required: ["personaId", "deviceId", "url", "emotion", "thought", "evidence"],
        optional: ["critiqueAxis", "stance", "respondsToPersonaId", "respondsToPersonaName", "responseReason", "responseReasonDetail", "sourceIds"],
        notes: [
          "`thought` is first-person agent output intended for visible report bubbles.",
          "`stance` and `respondsToPersonaId` describe agent-to-agent conversation, not forced disagreement.",
          "`sourceIds` link the reaction to comparison or market sources when outside reading shaped the judgment.",
        ],
      },
      recommendation: {
        required: ["priority", "title", "targetArea", "recommendation", "evidence"],
        optional: ["affectedPersonas", "affectedDevices", "relatedReactionIds", "sourceIds", "implementationWorkItem"],
        notes: [
          "`implementationWorkItem` should include an export title, affected region, implementation steps, and acceptance criteria when a fix can become work.",
          "`relatedReactionIds` preserves the agent exchange behind a fix when the runner can link it.",
          "`sourceIds` preserves comparison or market context that shaped the fix.",
        ],
      },
      screenEvidence: {
        required: ["id", "route", "url", "deviceId", "width", "height", "capturedAt", "altText"],
        optional: ["imageDataUrl", "annotations"],
        notes: [
          "`imageDataUrl` may be absent for lightweight or API-only reports.",
          "`annotations` identify visible headings, actions, forms, images, or regions that support a finding or recommendation.",
        ],
      },
      persistence: {
        statuses: ["persisted", "generated", "skipped", "failed"],
        notes: [
          "`persisted` means production storage accepted the run.",
          "`generated` is a development/session fallback and is not a customer-facing product path.",
          "`failed` should include a reason and should not hide credential or storage boundary problems.",
        ],
      },
    },
    automation: {
      selfAudit: {
        command: "corepack pnpm self-audit",
        artifactRoot: "docs/self-audits",
        exampleCommands: [
          "corepack pnpm self-audit -- --base-url http://127.0.0.1:3100 --cycle cycle-saved-agent --routes /agents,/runs/new --local-storage-file docs/self-audits/fixtures/saved-agent-local-storage.json",
          "corepack pnpm self-audit -- --base-url http://127.0.0.1:3100 --cycle cycle-inline-state --routes /runs/new --local-storage-json '{\"snoopy.savedAgents\":\"[]\"}'",
        ],
        localStorageSeeding: {
          cliFlags: ["--local-storage-file", "--local-storage-json"],
          envVars: ["SNOOPY_SELF_AUDIT_LOCAL_STORAGE_FILE", "SNOOPY_SELF_AUDIT_LOCAL_STORAGE_JSON"],
          fixture: "docs/self-audits/fixtures/saved-agent-local-storage.json",
          runHistoryFixture: "docs/self-audits/fixtures/saved-agent-with-run-history-local-storage.json",
          valueContract: "Pass a JSON object whose keys are localStorage keys and whose values are already-serialized strings.",
          exampleLocalStorageJson: {
            "snoopy.savedAgents":
              '[{"id":"custom-brand-guardian","name":"Brand Guardian","role":"Customer-owned brand guardian","face":"BG","voice":"Plainspoken, visual, and commercially strict","goal":"Protect premium brand quality while improving conversion.","backstory":"Generated for a customer that wants a durable agent with taste and memory.","memories":["Remembers when weak screenshots hurt trust.","Tracks whether each run feels more premium."],"tastes":["premium visuals","clear hierarchy","specific proof"],"blindSpots":["May over-protect visual polish when conversion clarity is more urgent.","Needs another agent to challenge whether the brand taste fits new buyers."],"motivations":["Protect customer taste","Find issues the core cast may miss"],"likes":["Evidence near claims","Visible before and after"],"deviceHabits":["Checks mobile first","Reviews evidence on desktop"],"skepticism":"Distrusts generic praise and generic criticism.","critiqueLens":["brand quality","visual hierarchy","customer-specific taste"],"voiceSettings":{"style":"plainspoken","profanityLevel":"none"},"personalityFacets":{"introversion":0.46,"extraversion":0.54,"sensing":0.62,"intuition":0.38,"thinking":0.58,"feeling":0.42,"judging":0.66,"perceiving":0.34},"dayPlan":["Read prior reports","Respond to another agent"],"sourceDiet":["Customer site history","Competitor pages"],"customerRelationship":"Private recurring reviewer for Acme Growth homepage quality.","privateExclusive":true,"customerOwned":true}]',
            "snoopy.agentRunHistory":
              '[{"id":"agent_test:custom-brand-guardian:desktop:0","runId":"agent_test","targetUrl":"https://example.com","completedAt":"2026-05-09T22:52:00.000Z","personaId":"custom-brand-guardian","personaName":"Brand Guardian","personaRole":"Customer-owned brand guardian","deviceId":"desktop","emotion":"curious","thought":"I can see the brand idea, but the proof needs to look more premium.","evidence":"The saved agent carried its brand-quality lens into the run.","critiqueAxis":"brand quality","stance":"extends_prior","respondsToPersonaId":"leo","respondsToPersonaName":"Leo","responseReason":"same_run_reply","responseReasonDetail":"Brand Guardian leans sensing/judging; Leo leans intuition/perceiving."}]',
          },
          purpose: "Evaluate browser-persisted product states such as saved customer-owned agents in run setup and agent pages.",
        },
      },
    },
    output: {
      reportFields: [
        "summary",
        "findings",
        "personas",
        "devices",
        "referenceSources",
        "disagreement",
        "journeyEvents",
        "reactions",
        "snapshots",
        "screenEvidence",
        "recommendations",
        "recommendations.implementationWorkItem",
        "beforeAfterHypotheses",
        "artifacts",
      ],
      beforeAfterHypothesisFields: ["id", "route", "currentSignal", "improvedSignal", "evidence", "personaId", "recommendationTitle"],
      screenEvidenceFields: ["id", "route", "url", "deviceId", "width", "height", "capturedAt", "imageDataUrl", "altText", "annotations"],
      screenEvidenceAnnotationFields: ["id", "kind", "label", "x", "y", "width", "height", "importance", "evidence"],
      recommendationWorkItemFields: ["exportTitle", "affectedRegion", "changeType", "implementationSteps", "acceptanceCriteria"],
      personaFields: [
        "id",
        "name",
        "role",
        "face",
        "goal",
        "backstory",
        "memories",
        "tastes",
        "blindSpots",
        "motivations",
        "likes",
        "deviceHabits",
        "skepticism",
        "critiqueLens",
        "voice",
        "personalityFacets",
        "sourceDiet",
        "dayPlan",
        "customerRelationship",
        "privateExclusive",
        "customerOwned",
      ],
      generatedAgentFields: [
        "id",
        "name",
        "role",
        "face",
        "voice",
        "goal",
        "backstory",
        "memories",
        "tastes",
        "blindSpots",
        "motivations",
        "likes",
        "deviceHabits",
        "skepticism",
        "critiqueLens",
        "voiceSettings",
        "personalityFacets",
        "dayPlan",
        "sourceDiet",
        "customerRelationship",
        "privateExclusive",
        "customerOwned",
      ],
      reactionFields: ["personaId", "deviceId", "url", "emotion", "thought", "evidence", "critiqueAxis", "stance", "respondsToPersonaId", "responseReason", "responseReasonDetail"],
      reactionStanceValues: ["independent", "supports_prior", "extends_prior", "contradicts_prior", "improved_since_prior"],
      reactionResponseReasonValues: ["same_run_reply", "prior_memory", "self_memory", "same_evidence", "polarity_shift", "prior_improvement", "facet_contrast"],
      artifactFields: ["id", "title", "kind", "format", "mediaType", "href", "fileName", "description", "itemCount"],
      artifactKinds: ["implementation_queue"],
      artifactPersistence: "Production persistence stores declared report artifacts in report_artifacts records while keeping the full artifact manifest in report payload JSON.",
      visibleReportActions: [
        "copy one recommendation as a fix handoff",
        "copy the full implementation plan with agent judgment context",
        "download the implementation plan as markdown",
      ],
      findingCategories: [
        "confusion",
        "dead_end",
        "trust_issue",
        "copy_problem",
        "conversion_friction",
        "accessibility",
        "visual_design",
        "agent_readiness",
        "suggested_fix",
      ],
      developerFallback: "When production persistence is not configured, validation runs may return persistence.status='generated' and can reopen only inside the running workspace session. This is not a customer plan.",
    },
    deployment: {
      docs: "docs/deployment.md",
      requiredProductionEnv: [
        "NEXT_PUBLIC_APP_URL",
        "NEXT_PUBLIC_SUPABASE_URL",
        "NEXT_PUBLIC_SUPABASE_ANON_KEY",
        "SUPABASE_SERVICE_ROLE_KEY",
        "SNOOPY_DEFAULT_WORKSPACE_ID",
      ],
      optionalIntegrationEnv: [
        "OPENAI_API_KEY",
        "OPENAI_AGENT_GENERATOR_MODEL",
        "GEMMA_OPENAI_BASE_URL",
        "GEMMA_OPENAI_API_KEY",
        "GEMMA_OPENAI_MODEL",
        "SNOOPY_DISABLE_GEMMA",
        "NEXT_PUBLIC_POSTHOG_PROJECT_TOKEN",
        "NEXT_PUBLIC_POSTHOG_HOST",
        "STRIPE_SECRET_KEY",
        "STRIPE_WEBHOOK_SECRET",
        "PLAYWRIGHT_HEADLESS",
      ],
      commands: {
        install: "corepack pnpm install --frozen-lockfile",
        build: "corepack pnpm build",
        start: "PORT=3000 corepack pnpm start",
        smoke: "PLAYWRIGHT_BASE_URL=https://your-snoopy-host.example corepack pnpm e2e:smoke",
      },
      boundaries: [
        "SUPABASE_SERVICE_ROLE_KEY, GEMMA_OPENAI_API_KEY, OPENAI_API_KEY, and Stripe secrets stay server-side.",
        "Development/session persistence is not a customer-facing product path.",
        "Production run persistence requires Supabase credentials and SNOOPY_DEFAULT_WORKSPACE_ID.",
      ],
    },
  });
}
